README.md

[Rendered markdown](https://github.com/signal-noise/stylelint-scales/blob/e5bbc9653c8bd03b610ec9f49bbf0b915c06886f/README.md#why).
Closes #9

Add rationale

---

README.md

Closes https://github.com/signal-noise/stylelint-scales/issues/12

Fix plugin name in example

---

.github/workflows/nodejs.yml

Enable multi-platform testing.

CI Platforms Support

---

CHANGELOG.md
lib/reference/valueSets.js
lib/rules/font-size/README.md
lib/rules/font-size/__tests__/index.js
lib/rules/font-size/index.js
lib/rules/space/README.md
lib/rules/space/__tests__/index.js
lib/rules/space/index.js
package-lock.json

Change <length>-based rules to support more units

---

README.md

Badges for NPM version and download count.

Adding NPM related badges

---

package-lock.json
package.json

- Updated stylelint and eslint packages.
- Added release -> np script.
- Changed linting and fix sub task names.

Updated packages and changed scripts

---

CHANGELOG.md

Changed changelog to reflect version bump to 1.0.0

Change change log

---

.github/CODEOWNERS
CHANGELOG.md
README.md
lib/index.js
lib/rules/font-family/README.md
lib/rules/font-family/__tests__/index.js
lib/rules/font-family/index.js
lib/rules/letter-spacing/README.md
lib/rules/letter-spacing/__tests__/index.js
lib/rules/letter-spacing/index.js
lib/rules/radii/README.md
lib/rules/radii/__tests__/index.js
lib/rules/radii/index.js
lib/rules/word-spacing/README.md
lib/rules/word-spacing/__tests__/index.js
lib/rules/word-spacing/index.js
package-lock.json
package.json

Adding extra scales:
- letter spacings
- word spacings 
- fonts
- radii
Check #8

Add extra scales

---

.github/workflows/nodejs.yml
lib/rules/color/README.md
lib/rules/color/__tests__/index.js
package-lock.json
package.json

Linting step in CI on Windows only was returning errors. This removes the linting script from Windows, retaining it on unix OSs. 
No

Removes linting from Windows CI 

---

CHANGELOG.md
lib/rules/font-family/README.md
lib/rules/font-family/__tests__/index.js
lib/rules/font-family/index.js
lib/utils/parseShorthandFont.js
package-lock.json
package.json

Fixes #36 -  "inherit" declarations now bypass `parse-css-font` library. 
No

Handle `font: inherit`

---

CHANGELOG.md
lib/rules/border-width/__tests__/index.js
lib/rules/border-width/__tests__/withUnits.js
lib/rules/border-width/index.js
lib/rules/color/index.js
lib/rules/font-family/index.js
lib/rules/font-size/__tests__/index.js
lib/rules/font-size/__tests__/withUnits.js
lib/rules/font-size/index.js
lib/rules/font-weight/index.js
lib/rules/letter-spacing/__tests__/index.js
lib/rules/letter-spacing/__tests__/withUnits.js
lib/rules/letter-spacing/index.js
lib/rules/line-height/index.js
lib/rules/radii/__tests__/index.js
lib/rules/radii/__tests__/withUnits.js
lib/rules/radii/index.js
lib/rules/sizes/__tests__/index.js
lib/rules/sizes/__tests__/withUnits.js
lib/rules/sizes/index.js
lib/rules/space/__tests__/index.js
lib/rules/space/__tests__/withUnits.js
lib/rules/space/index.js
lib/rules/word-spacing/__tests__/index.js
lib/rules/word-spacing/__tests__/withUnits.js
lib/rules/word-spacing/index.js
lib/rules/z-indices/index.js
lib/utils/generateStandardRuleMessage.js

Closes #42 
Added units to the message output upon rule breaking.

Adds units to rule messages

---

CHANGELOG.md

None, as it's a documentation fix.
It's fantastic to see this package getting some love over the last year or so! 
This pull request updates the changelog to show the [types of changes](https://keepachangelog.com/en/1.0.0/#how). Making this pull request has helped me understand what changes have been made to the package since I last looked.
(As an aside, it also shows that 1.5.0 should have probably been 2.0.0 as it included the "Removed" type of change.)

Fix changelog structure to be consistent

---

package-lock.json
package.json

Use local np for releases

---

.github/workflows/nodejs.yml

None.
Node.js 14 is [LTS Active](https://nodejs.org/en/about/releases/).

Add node.js 14 to CI

---

.eslintrc
README.md
lib/rules/font-sizes/README.md
lib/rules/font-sizes/__tests__/index.js
lib/rules/font-sizes/index.js
lib/utils/hasObjectWithNumericArray.js

Add `ignoreFunctionArguments` to `font-sizes`

---

CHANGELOG.md
README.md
package-lock.json
package.json

Change package name

---

.github/workflows/nodejs.yml

None
No, it's self explanatory.

Update workflow to use `main` branch

---

lib/rules/alpha-values/index.js
lib/rules/border-widths/index.js
lib/rules/font-sizes/index.js
lib/rules/font-weights/index.js
lib/rules/letter-spacings/index.js
lib/rules/line-heights/index.js
lib/rules/radii/index.js
lib/rules/sizes/index.js
lib/rules/space/index.js
lib/rules/word-spacings/index.js
lib/rules/z-indices/index.js
package-lock.json
package.json

Closes #98 
The `fix` callback update requires Stylelint v16.8.2.

Change autofix to use `fix()` callback

---

CHANGELOG.md

Prepare 5.0.0 changelog

---

CHANGELOG.md
package.json

Fixed npm published files to exclude READMEs and tests
